services:
  postgres:
    image: postgres:17-alpine
    restart: no
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expensesTracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

volumes:
 postgres_data2: